apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: new-pipeline
  namespace: sn-labs-rfuentes
spec:
  workspaces:
    - name: output
  params:
    - name: repo-url
      type: string
      description: The URL to the GitHub repo
    - name: branch
      type: string
      default: main
    - name: app-name
      type: string
      description: Name of the application/deployment
    - name: build-image
      type: string
      description: The image to build and deploy
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: git-clone
      runAfter:
        - cleanup
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: output
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)

    - name: flake8
      runAfter:
        - git-clone
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: output

    - name: nose
      runAfter:
        - flake8
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: output

    - name: buildah
      runAfter:
        - nose
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: output

    - name: deploy
      runAfter:
        - buildah
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
      workspaces:
        - name: manifest-dir
          workspace: output